-- ============================================================================
-- Migration: Create suggestions table
-- Description: Store AI-generated English expression suggestions
-- ============================================================================

-- Create suggestions table
CREATE TABLE IF NOT EXISTS public.suggestions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    chat_message_id BIGINT NOT NULL REFERENCES public.chat_messages(id) ON DELETE CASCADE,
    english_sentence TEXT NOT NULL,
    japanese_translation TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Add comment to table
COMMENT ON TABLE public.suggestions IS 'AI-generated English expression suggestions linked to chat messages';

-- Add comments to columns
COMMENT ON COLUMN public.suggestions.id IS 'Unique identifier for each suggestion';
COMMENT ON COLUMN public.suggestions.user_id IS 'User who owns this suggestion';
COMMENT ON COLUMN public.suggestions.chat_message_id IS 'Chat message that contains this suggestion';
COMMENT ON COLUMN public.suggestions.english_sentence IS 'English example sentence';
COMMENT ON COLUMN public.suggestions.japanese_translation IS 'Japanese translation of the English sentence';
COMMENT ON COLUMN public.suggestions.created_at IS 'Timestamp when the suggestion was created';
COMMENT ON COLUMN public.suggestions.updated_at IS 'Timestamp when the suggestion was last updated';

-- ============================================================================
-- Row Level Security (RLS)
-- ============================================================================

-- Enable RLS
ALTER TABLE public.suggestions ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view their own suggestions
CREATE POLICY "Users can view their own suggestions"
    ON public.suggestions
    FOR SELECT
    USING (auth.uid() = user_id);

-- Policy: Users can insert their own suggestions
CREATE POLICY "Users can insert their own suggestions"
    ON public.suggestions
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Policy: Users can update their own suggestions
CREATE POLICY "Users can update their own suggestions"
    ON public.suggestions
    FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Policy: Users can delete their own suggestions
CREATE POLICY "Users can delete their own suggestions"
    ON public.suggestions
    FOR DELETE
    USING (auth.uid() = user_id);

-- ============================================================================
-- Triggers
-- ============================================================================

-- Trigger: Auto-update updated_at on suggestions
CREATE TRIGGER set_updated_at
    BEFORE UPDATE ON public.suggestions
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- ============================================================================
-- Indexes
-- ============================================================================

-- Index on user_id for filtering user's suggestions
CREATE INDEX IF NOT EXISTS idx_suggestions_user_id ON public.suggestions(user_id);

-- Index on chat_message_id for fetching suggestions by message
CREATE INDEX IF NOT EXISTS idx_suggestions_chat_message_id ON public.suggestions(chat_message_id);

-- Composite index for user's suggestions sorted by date
CREATE INDEX IF NOT EXISTS idx_suggestions_user_id_created_at 
    ON public.suggestions(user_id, created_at DESC);

-- Composite index for message's suggestions
CREATE INDEX IF NOT EXISTS idx_suggestions_chat_message_id_created_at 
    ON public.suggestions(chat_message_id, created_at DESC);

-- ============================================================================
-- Rollback (commented out - uncomment if needed)
-- ============================================================================
-- DROP TRIGGER IF EXISTS set_updated_at ON public.suggestions;
-- DROP INDEX IF EXISTS idx_suggestions_chat_message_id_created_at;
-- DROP INDEX IF EXISTS idx_suggestions_user_id_created_at;
-- DROP INDEX IF EXISTS idx_suggestions_chat_message_id;
-- DROP INDEX IF EXISTS idx_suggestions_user_id;
-- DROP POLICY IF EXISTS "Users can delete their own suggestions" ON public.suggestions;
-- DROP POLICY IF EXISTS "Users can update their own suggestions" ON public.suggestions;
-- DROP POLICY IF EXISTS "Users can insert their own suggestions" ON public.suggestions;
-- DROP POLICY IF EXISTS "Users can view their own suggestions" ON public.suggestions;
-- DROP TABLE IF EXISTS public.suggestions;

