-- chat_groups テーブルの作成
CREATE TABLE chat_groups (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- インデックスの作成
CREATE INDEX idx_chat_groups_user_id ON chat_groups(user_id);
CREATE INDEX idx_chat_groups_created_at ON chat_groups(created_at DESC);

-- RLS (Row Level Security) の有効化
ALTER TABLE chat_groups ENABLE ROW LEVEL SECURITY;

-- RLS ポリシー: ユーザーは自分のチャットグループのみ閲覧可能
CREATE POLICY "Users can view their own chat groups"
  ON chat_groups
  FOR SELECT
  USING (auth.uid() = user_id);

-- RLS ポリシー: ユーザーは自分のチャットグループを作成可能
CREATE POLICY "Users can create their own chat groups"
  ON chat_groups
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- RLS ポリシー: ユーザーは自分のチャットグループを更新可能
CREATE POLICY "Users can update their own chat groups"
  ON chat_groups
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- RLS ポリシー: ユーザーは自分のチャットグループを削除可能
CREATE POLICY "Users can delete their own chat groups"
  ON chat_groups
  FOR DELETE
  USING (auth.uid() = user_id);

-- updated_at の自動更新トリガー
CREATE OR REPLACE FUNCTION update_chat_groups_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_chat_groups_updated_at
  BEFORE UPDATE ON chat_groups
  FOR EACH ROW
  EXECUTE FUNCTION update_chat_groups_updated_at();

