-- chat_messages テーブルの作成
CREATE TABLE chat_messages (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  chat_group_id BIGINT NOT NULL REFERENCES chat_groups(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  role VARCHAR(50) NOT NULL CHECK (role IN ('user', 'ai')),
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- インデックスの作成
CREATE INDEX idx_chat_messages_chat_group_id ON chat_messages(chat_group_id);
CREATE INDEX idx_chat_messages_user_id ON chat_messages(user_id);
CREATE INDEX idx_chat_messages_created_at ON chat_messages(created_at);

-- RLS (Row Level Security) の有効化
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;

-- RLS ポリシー: ユーザーは自分のチャットグループのメッセージのみ閲覧可能
CREATE POLICY "Users can view messages in their own chat groups"
  ON chat_messages
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM chat_groups
      WHERE chat_groups.id = chat_messages.chat_group_id
      AND chat_groups.user_id = auth.uid()
    )
  );

-- RLS ポリシー: ユーザーは自分のチャットグループにメッセージを作成可能
CREATE POLICY "Users can create messages in their own chat groups"
  ON chat_messages
  FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM chat_groups
      WHERE chat_groups.id = chat_messages.chat_group_id
      AND chat_groups.user_id = auth.uid()
    )
  );

-- RLS ポリシー: ユーザーは自分のチャットグループのメッセージを更新可能
CREATE POLICY "Users can update messages in their own chat groups"
  ON chat_messages
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM chat_groups
      WHERE chat_groups.id = chat_messages.chat_group_id
      AND chat_groups.user_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM chat_groups
      WHERE chat_groups.id = chat_messages.chat_group_id
      AND chat_groups.user_id = auth.uid()
    )
  );

-- RLS ポリシー: ユーザーは自分のチャットグループのメッセージを削除可能
CREATE POLICY "Users can delete messages in their own chat groups"
  ON chat_messages
  FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM chat_groups
      WHERE chat_groups.id = chat_messages.chat_group_id
      AND chat_groups.user_id = auth.uid()
    )
  );

-- updated_at の自動更新トリガー
CREATE OR REPLACE FUNCTION update_chat_messages_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_chat_messages_updated_at
  BEFORE UPDATE ON chat_messages
  FOR EACH ROW
  EXECUTE FUNCTION update_chat_messages_updated_at();

