-- ============================================================================
-- Migration: Create chat_messages table
-- Description: Store chat conversation history between users and AI
-- ============================================================================

-- Create chat_messages table
CREATE TABLE IF NOT EXISTS public.chat_messages (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    role VARCHAR(50) NOT NULL CHECK (role IN ('user', 'ai')),
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Add comment to table
COMMENT ON TABLE public.chat_messages IS 'Chat conversation history between users and AI';

-- Add comments to columns
COMMENT ON COLUMN public.chat_messages.id IS 'Unique identifier for each message';
COMMENT ON COLUMN public.chat_messages.user_id IS 'User who sent the message (NULL for AI messages)';
COMMENT ON COLUMN public.chat_messages.role IS 'Role of the message sender: user or ai';
COMMENT ON COLUMN public.chat_messages.message IS 'Content of the message';
COMMENT ON COLUMN public.chat_messages.created_at IS 'Timestamp when the message was created';
COMMENT ON COLUMN public.chat_messages.updated_at IS 'Timestamp when the message was last updated';

-- ============================================================================
-- Row Level Security (RLS)
-- ============================================================================

-- Enable RLS
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view their own messages and AI messages
CREATE POLICY "Users can view their own messages"
    ON public.chat_messages
    FOR SELECT
    USING (
        auth.uid() = user_id OR 
        user_id IS NULL  -- AI messages
    );

-- Policy: Users can insert their own messages
CREATE POLICY "Users can insert their own messages"
    ON public.chat_messages
    FOR INSERT
    WITH CHECK (auth.uid() = user_id AND role = 'user');

-- Policy: Users can update their own messages
CREATE POLICY "Users can update their own messages"
    ON public.chat_messages
    FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Policy: Users can delete their own messages
CREATE POLICY "Users can delete their own messages"
    ON public.chat_messages
    FOR DELETE
    USING (auth.uid() = user_id);

-- ============================================================================
-- Triggers
-- ============================================================================

-- Trigger: Auto-update updated_at on chat_messages
CREATE TRIGGER set_updated_at
    BEFORE UPDATE ON public.chat_messages
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- ============================================================================
-- Indexes
-- ============================================================================

-- Index on user_id for filtering user's messages
CREATE INDEX IF NOT EXISTS idx_chat_messages_user_id ON public.chat_messages(user_id);

-- Index on created_at for sorting messages chronologically
CREATE INDEX IF NOT EXISTS idx_chat_messages_created_at ON public.chat_messages(created_at DESC);

-- Composite index for user's messages sorted by date
CREATE INDEX IF NOT EXISTS idx_chat_messages_user_id_created_at 
    ON public.chat_messages(user_id, created_at DESC);

-- Index on role for filtering by message type
CREATE INDEX IF NOT EXISTS idx_chat_messages_role ON public.chat_messages(role);

-- ============================================================================
-- Rollback (commented out - uncomment if needed)
-- ============================================================================
-- DROP TRIGGER IF EXISTS set_updated_at ON public.chat_messages;
-- DROP INDEX IF EXISTS idx_chat_messages_role;
-- DROP INDEX IF EXISTS idx_chat_messages_user_id_created_at;
-- DROP INDEX IF EXISTS idx_chat_messages_created_at;
-- DROP INDEX IF EXISTS idx_chat_messages_user_id;
-- DROP POLICY IF EXISTS "Users can delete their own messages" ON public.chat_messages;
-- DROP POLICY IF EXISTS "Users can update their own messages" ON public.chat_messages;
-- DROP POLICY IF EXISTS "Users can insert their own messages" ON public.chat_messages;
-- DROP POLICY IF EXISTS "Users can view their own messages" ON public.chat_messages;
-- DROP TABLE IF EXISTS public.chat_messages;

