-- ============================================================================
-- Migration: Create bookmarks table
-- Description: Manage user bookmarks for suggestions
-- ============================================================================

-- Create bookmarks table
CREATE TABLE IF NOT EXISTS public.bookmarks (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    suggestion_id BIGINT NOT NULL REFERENCES public.suggestions(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT unique_user_suggestion UNIQUE (user_id, suggestion_id)
);

-- Add comment to table
COMMENT ON TABLE public.bookmarks IS 'User bookmarks for English expression suggestions';

-- Add comments to columns
COMMENT ON COLUMN public.bookmarks.id IS 'Unique identifier for each bookmark';
COMMENT ON COLUMN public.bookmarks.user_id IS 'User who created the bookmark';
COMMENT ON COLUMN public.bookmarks.suggestion_id IS 'Suggestion that was bookmarked';
COMMENT ON COLUMN public.bookmarks.created_at IS 'Timestamp when the bookmark was created';
COMMENT ON COLUMN public.bookmarks.updated_at IS 'Timestamp when the bookmark was last updated';

-- ============================================================================
-- Row Level Security (RLS)
-- ============================================================================

-- Enable RLS
ALTER TABLE public.bookmarks ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view their own bookmarks
CREATE POLICY "Users can view their own bookmarks"
    ON public.bookmarks
    FOR SELECT
    USING (auth.uid() = user_id);

-- Policy: Users can insert their own bookmarks
CREATE POLICY "Users can insert their own bookmarks"
    ON public.bookmarks
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Policy: Users can update their own bookmarks
CREATE POLICY "Users can update their own bookmarks"
    ON public.bookmarks
    FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Policy: Users can delete their own bookmarks
CREATE POLICY "Users can delete their own bookmarks"
    ON public.bookmarks
    FOR DELETE
    USING (auth.uid() = user_id);

-- ============================================================================
-- Triggers
-- ============================================================================

-- Trigger: Auto-update updated_at on bookmarks
CREATE TRIGGER set_updated_at
    BEFORE UPDATE ON public.bookmarks
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- ============================================================================
-- Indexes
-- ============================================================================

-- Index on user_id for filtering user's bookmarks
CREATE INDEX IF NOT EXISTS idx_bookmarks_user_id ON public.bookmarks(user_id);

-- Index on suggestion_id for checking if a suggestion is bookmarked
CREATE INDEX IF NOT EXISTS idx_bookmarks_suggestion_id ON public.bookmarks(suggestion_id);

-- Composite index for user's bookmarks sorted by date
CREATE INDEX IF NOT EXISTS idx_bookmarks_user_id_created_at 
    ON public.bookmarks(user_id, created_at DESC);

-- Index on unique constraint (automatically created, but explicit for clarity)
-- CREATE UNIQUE INDEX IF NOT EXISTS idx_bookmarks_unique_user_suggestion 
--     ON public.bookmarks(user_id, suggestion_id);

-- ============================================================================
-- Rollback (commented out - uncomment if needed)
-- ============================================================================
-- DROP TRIGGER IF EXISTS set_updated_at ON public.bookmarks;
-- DROP INDEX IF EXISTS idx_bookmarks_user_id_created_at;
-- DROP INDEX IF EXISTS idx_bookmarks_suggestion_id;
-- DROP INDEX IF EXISTS idx_bookmarks_user_id;
-- DROP POLICY IF EXISTS "Users can delete their own bookmarks" ON public.bookmarks;
-- DROP POLICY IF EXISTS "Users can update their own bookmarks" ON public.bookmarks;
-- DROP POLICY IF EXISTS "Users can insert their own bookmarks" ON public.bookmarks;
-- DROP POLICY IF EXISTS "Users can view their own bookmarks" ON public.bookmarks;
-- DROP TABLE IF EXISTS public.bookmarks;

